PFF/ASP/gestionAbsenceMVC/gestionAbsenceMVC/Models/Prof.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionAbsenceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prof
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prof()
        {
            this.Absences = new HashSet<Absence>();
        }
    
        public int id_P { get; set; }
        public string nom_P { get; set; }
        public string prenom_P { get; set; }
        public string sexe_P { get; set; }
        public Nullable<int> id_M { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Absence> Absences { get; set; }
        public virtual matiere matiere { get; set; }
    }
}

PFF/ASP/gestionAbsenceMVC/gestionAbsenceMVC/Controllers/ProfsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using gestionAbsenceMVC.Models;

namespace gestionAbsenceMVC.Controllers
{
    public class ProfsController : Controller
    {
        private GesAbsEntities6 db = new GesAbsEntities6();

        // GET: Profs
        public ActionResult Index(string search,string searchBy)
        {
            var profs = db.Profs.Include(p => p.matiere);
            if (searchBy == "Name") { var resultofSearch = db.Profs.Where(x => x.nom_P.StartsWith(search) || search == null); return View(resultofSearch.ToList()); }
            if (searchBy == "Gender") { var resultofSearch = db.Profs.Where(x => x.sexe_P.StartsWith(search) || search == null); return View(resultofSearch.ToList()); }
            if (searchBy == "Matiere") { var resultofSearch = db.Profs.Where(x => x.matiere.libelle.StartsWith(search) || search == null); return View(resultofSearch.ToList()); }
            return View(profs.ToList());
        }

        // GET: Profs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prof prof = db.Profs.Find(id);
            if (prof == null)
            {
                return HttpNotFound();
            }
            return View(prof);
        }

        // GET: Profs/Create
        public ActionResult Create()
        {
            ViewBag.id_M = new SelectList(db.matieres, "id_M", "libelle");
            return View();
        }

        // POST: Profs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_P,nom_P,prenom_P,sexe_P,id_M")] Prof prof)
        {
            if (ModelState.IsValid)
            {
                db.Profs.Add(prof);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_M = new SelectList(db.matieres, "id_M", "libelle", prof.id_M);
            return View(prof);
        }

        // GET: Profs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prof prof = db.Profs.Find(id);
            if (prof == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_M = new SelectList(db.matieres, "id_M", "libelle", prof.id_M);
            return View(prof);
        }

        // POST: Profs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_P,nom_P,prenom_P,sexe_P,id_M")] Prof prof)
        {
            if (ModelState.IsValid)
            {
                db.Entry(prof).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_M = new SelectList(db.matieres, "id_M", "libelle", prof.id_M);
            return View(prof);
        }

        // GET: Profs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prof prof = db.Profs.Find(id);
            if (prof == null)
            {
                return HttpNotFound();
            }
            return View(prof);
        }

        // POST: Profs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Prof prof = db.Profs.Find(id);
            db.Profs.Remove(prof);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PFF/ASP/gestionAbsenceMVC/gestionAbsenceMVC/Views/Profs/Create.cshtml
@model gestionAbsenceMVC.Models.Prof

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Prof</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nom_P, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom_P, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom_P, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prenom_P, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prenom_P, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prenom_P, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sexe_P, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.sexe_P, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("sexe_P", new List<SelectListItem>
    {new SelectListItem  {Text="MALE",Selected=true},new SelectListItem  {Text="FEMALE"},}, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.sexe_P, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_M, "id_M", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_M", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_M, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PFF/ASP/gestionAbsenceMVC/gestionAbsenceMVC/Views/Profs/Delete.cshtml
@model gestionAbsenceMVC.Models.Prof

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Prof</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nom_P)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom_P)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prenom_P)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prenom_P)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sexe_P)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sexe_P)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.matiere.libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.matiere.libelle)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PFF/ASP/gestionAbsenceMVC/gestionAbsenceMVC/Views/Profs/Details.cshtml
@model gestionAbsenceMVC.Models.Prof

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Prof</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nom_P)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom_P)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prenom_P)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prenom_P)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sexe_P)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sexe_P)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.matiere.libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.matiere.libelle)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_P }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PFF/ASP/gestionAbsenceMVC/gestionAbsenceMVC/Views/Profs/Edit.cshtml
@model gestionAbsenceMVC.Models.Prof

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Prof</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_P)

        <div class="form-group">
            @Html.LabelFor(model => model.nom_P, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom_P, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom_P, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prenom_P, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prenom_P, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prenom_P, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sexe_P, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.sexe_P, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("sexe_P", new List<SelectListItem>
{new SelectListItem  {Text="MALE",Selected=true},new SelectListItem  {Text="FEMALE"},}, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.sexe_P, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_M, "id_M", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_M", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_M, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PFF/ASP/gestionAbsenceMVC/gestionAbsenceMVC/Views/Profs/Index.cshtml
@model IEnumerable<gestionAbsenceMVC.Models.Prof>

@{
    ViewBag.Title = "Index";
}

<h2>Professor</h2>

<p>
    @Html.ActionLink("Create New", "Create")

</p>
<div class="form-horizontal">
    @using (Html.BeginForm("Index", "Profs", FormMethod.Get))
    {<b>search by :</b>
        @Html.RadioButton("searchBy", "Name", true)<text>  Name  </text>
        @Html.RadioButton("searchBy", "Gender")<text>  Gender  </text>
        @Html.RadioButton("searchBy", "Matiere")<text>  Matiere  </text>

        <p>
            @Html.TextBox("search")  <input type="submit" value="search" />
        </p>
    }

</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nom_P)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prenom_P)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.sexe_P)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.matiere.libelle)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nom_P)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.prenom_P)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.sexe_P)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.matiere.libelle)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id_P }) |
            @Html.ActionLink("Details", "Details", new { id=item.id_P }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id_P })
        </td>
    </tr>
}

</table>