PFF/ASP/gestionAbsenceMVC/gestionAbsenceMVC/Models/Stagiare.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionAbsenceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stagiare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stagiare()
        {
            this.Absences = new HashSet<Absence>();
        }
    
        public int id_S { get; set; }
        public string nom_S { get; set; }
        public string prenom_S { get; set; }
        public string sexe_S { get; set; }
        public Nullable<int> id_G { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Absence> Absences { get; set; }
        public virtual Groupe Groupe { get; set; }
    }
}

PFF/ASP/gestionAbsenceMVC/gestionAbsenceMVC/Controllers/StagiaresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using gestionAbsenceMVC.Models;

namespace gestionAbsenceMVC.Controllers
{
    public class StagiaresController : Controller
    {
        private GesAbsEntities6 db = new GesAbsEntities6();

        // GET: Stagiares
        public ActionResult Index(string search,string searchBy)
        {
            var stagiares = db.Stagiares.Include(s => s.Groupe);
            if (searchBy == "Name") { var resultofSearch = db.Stagiares.Where(x => x.nom_S.StartsWith(search) || search == null); return View(resultofSearch.ToList()); }
            if (searchBy == "Gender") { var resultofSearch = db.Stagiares.Where(x => x.sexe_S.StartsWith(search) || search == null); return View(resultofSearch.ToList()); }
            if (searchBy == "Groupe") { var resultofSearch = db.Stagiares.Where(x => x.Groupe.nom_G.StartsWith(search) || search == null); return View(resultofSearch.ToList()); }
            return View(stagiares.ToList());



        }

        // GET: Stagiares/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stagiare stagiare = db.Stagiares.Find(id);
            if (stagiare == null)
            {
                return HttpNotFound();
            }
            return View(stagiare);
        }

        // GET: Stagiares/Create
        public ActionResult Create()
        {
            ViewBag.id_G = new SelectList(db.Groupes, "id_G", "nom_G");
            return View();
        }

        // POST: Stagiares/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_S,nom_S,prenom_S,sexe_S,id_G")] Stagiare stagiare)
        {
            if (ModelState.IsValid)
            {
                db.Stagiares.Add(stagiare);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_G = new SelectList(db.Groupes, "id_G", "nom_G", stagiare.id_G);
            return View(stagiare);
        }

        // GET: Stagiares/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stagiare stagiare = db.Stagiares.Find(id);
            if (stagiare == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_G = new SelectList(db.Groupes, "id_G", "nom_G", stagiare.id_G);
            return View(stagiare);
        }

        // POST: Stagiares/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_S,nom_S,prenom_S,sexe_S,id_G")] Stagiare stagiare)
        {
            if (ModelState.IsValid)
            {
                db.Entry(stagiare).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_G = new SelectList(db.Groupes, "id_G", "nom_G", stagiare.id_G);
            return View(stagiare);
        }

        // GET: Stagiares/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stagiare stagiare = db.Stagiares.Find(id);
            if (stagiare == null)
            {
                return HttpNotFound();
            }
            return View(stagiare);
        }

        // POST: Stagiares/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Stagiare stagiare = db.Stagiares.Find(id);
            db.Stagiares.Remove(stagiare);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PFF/ASP/gestionAbsenceMVC/gestionAbsenceMVC/Views/Stagiares/Create.cshtml
@model gestionAbsenceMVC.Models.Stagiare

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Stagiare</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nom_S, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom_S, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom_S, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prenom_S, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prenom_S, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prenom_S, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sexe_S, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.sexe_S, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("sexe_S", new List<SelectListItem>
{new SelectListItem  {Text="MALE",Selected=true},new SelectListItem  {Text="FEMALE"},}, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.sexe_S, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_G, "id_G", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_G", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_G, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PFF/ASP/gestionAbsenceMVC/gestionAbsenceMVC/Views/Stagiares/Delete.cshtml
@model gestionAbsenceMVC.Models.Stagiare

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Stagiare</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nom_S)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom_S)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prenom_S)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prenom_S)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sexe_S)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sexe_S)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Groupe.nom_G)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Groupe.nom_G)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PFF/ASP/gestionAbsenceMVC/gestionAbsenceMVC/Views/Stagiares/Details.cshtml
@model gestionAbsenceMVC.Models.Stagiare

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Stagiare</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nom_S)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom_S)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prenom_S)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prenom_S)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sexe_S)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sexe_S)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Groupe.nom_G)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Groupe.nom_G)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_S }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PFF/ASP/gestionAbsenceMVC/gestionAbsenceMVC/Views/Stagiares/Edit.cshtml
@model gestionAbsenceMVC.Models.Stagiare

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Stagiare</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_S)

        <div class="form-group">
            @Html.LabelFor(model => model.nom_S, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom_S, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom_S, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prenom_S, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prenom_S, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prenom_S, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sexe_S, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.sexe_S, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("sexe_S", new List<SelectListItem>
{new SelectListItem  {Text="MALE",Selected=true},new SelectListItem  {Text="FEMALE"},}, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.sexe_S, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_G, "id_G", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_G", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_G, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PFF/ASP/gestionAbsenceMVC/gestionAbsenceMVC/Views/Stagiares/Index.cshtml
@model IEnumerable<gestionAbsenceMVC.Models.Stagiare>

@{
    ViewBag.Title = "Index";
}

<h2>Stagiaire</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="form-horizontal">
    @using (Html.BeginForm("Index", "Stagiares", FormMethod.Get))
    {<b>search by :</b>
        @Html.RadioButton("searchBy", "Name", true)<text>  Name  </text>
        @Html.RadioButton("searchBy", "Gender")<text>  Gender  </text>
        @Html.RadioButton("searchBy", "Groupe")<text>  Groupe  </text>

        <p>
            @Html.TextBox("search")  <input type="submit" value="search" />
        </p>
    }

</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nom_S)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prenom_S)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.sexe_S)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Groupe.nom_G)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nom_S)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.prenom_S)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.sexe_S)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Groupe.nom_G)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id_S }) |
            @Html.ActionLink("Details", "Details", new { id=item.id_S }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id_S })
        </td>
    </tr>
}

</table>