PFF/ASP/gestionAbsenceMVC/gestionAbsenceMVC/Models/Absence.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionAbsenceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absence
    {
        public int id_A { get; set; }
        public Nullable<System.DateTime> DateA { get; set; }
        public string type_Ab { get; set; }
        public Nullable<int> id_S { get; set; }
        public Nullable<int> id_P { get; set; }
        public string justf { get; set; }
    
        public virtual Prof Prof { get; set; }
        public virtual Stagiare Stagiare { get; set; }
    }
}

PFF/ASP/gestionAbsenceMVC/gestionAbsenceMVC/Controllers/AbsencesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using gestionAbsenceMVC.Models;

namespace gestionAbsenceMVC.Controllers
{
    public class AbsencesController : Controller
    {
        private GesAbsEntities6 db = new GesAbsEntities6();

        // GET: Absences
        public ActionResult Index(string search,string searchBy)
        {
            var absences = db.Absences.Include(a => a.Prof).Include(a => a.Stagiare);
            if (searchBy == "NameT") { var resultofSearch = db.Absences.Where(x => x.Stagiare.nom_S.StartsWith(search) || search == null); return View(resultofSearch.ToList()); }
            if (searchBy == "Date") { var resultofSearch = db.Absences.Where(x =>x.DateA!=null); return View(resultofSearch.ToList()); }
            if (searchBy == "NameP") { var resultofSearch = db.Absences.Where(x => x.Prof.nom_P.StartsWith(search) || search == null); return View(resultofSearch.ToList()); }
            if (searchBy == "Jus") { var resultofSearch = db.Absences.Where(x => x.justf.StartsWith(search) || search == null); return View(resultofSearch.ToList()); }
            if (searchBy == "Tyabs") { var resultofSearch = db.Absences.Where(x => x.type_Ab.StartsWith(search) || search == null); return View(resultofSearch.ToList()); }

            return View(absences.ToList());
        }

        // GET: Absences/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Absence absence = db.Absences.Find(id);
            if (absence == null)
            {
                return HttpNotFound();
            }
            return View(absence);
        }

        // GET: Absences/Create
        public ActionResult Create()
        {
            ViewBag.id_P = new SelectList(db.Profs, "id_P", "nom_P");
            ViewBag.id_S = new SelectList(db.Stagiares, "id_S", "nom_S");
            return View();
        }

        // POST: Absences/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_A,DateA,type_Ab,id_S,id_P,justf")] Absence absence)
        {
            if (ModelState.IsValid)
            {
                db.Absences.Add(absence);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_P = new SelectList(db.Profs, "id_P", "nom_P", absence.id_P);
            ViewBag.id_S = new SelectList(db.Stagiares, "id_S", "nom_S", absence.id_S);
            return View(absence);
        }

        // GET: Absences/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Absence absence = db.Absences.Find(id);
            if (absence == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_P = new SelectList(db.Profs, "id_P", "nom_P", absence.id_P);
            ViewBag.id_S = new SelectList(db.Stagiares, "id_S", "nom_S", absence.id_S);
            return View(absence);
        }

        // POST: Absences/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_A,DateA,type_Ab,id_S,id_P,justf")] Absence absence)
        {
            if (ModelState.IsValid)
            {
                db.Entry(absence).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_P = new SelectList(db.Profs, "id_P", "nom_P", absence.id_P);
            ViewBag.id_S = new SelectList(db.Stagiares, "id_S", "nom_S", absence.id_S);
            return View(absence);
        }

        // GET: Absences/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Absence absence = db.Absences.Find(id);
            if (absence == null)
            {
                return HttpNotFound();
            }
            return View(absence);
        }

        // POST: Absences/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Absence absence = db.Absences.Find(id);
            db.Absences.Remove(absence);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PFF/ASP/gestionAbsenceMVC/gestionAbsenceMVC/Views/Absences/Create.cshtml
@model gestionAbsenceMVC.Models.Absence

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Absence</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DateA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.type_Ab, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.type_Ab, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.type_Ab, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_S, "id_S", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_S", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_S, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_P, "id_P", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_P", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_P, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.justf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.justf, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("justf", new List<SelectListItem>
                {new SelectListItem  {Text="oui",Selected=true},new SelectListItem  {Text="non"},},htmlAttributes:new {@class= "form-control" })

                @Html.ValidationMessageFor(model => model.justf, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PFF/ASP/gestionAbsenceMVC/gestionAbsenceMVC/Views/Absences/Delete.cshtml
@model gestionAbsenceMVC.Models.Absence

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Absence</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.type_Ab)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.type_Ab)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.justf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.justf)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prof.nom_P)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prof.nom_P)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stagiare.nom_S)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stagiare.nom_S)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PFF/ASP/gestionAbsenceMVC/gestionAbsenceMVC/Views/Absences/Details.cshtml
@model gestionAbsenceMVC.Models.Absence

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Absence</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.type_Ab)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.type_Ab)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.justf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.justf)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prof.nom_P)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prof.nom_P)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stagiare.nom_S)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stagiare.nom_S)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_A }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PFF/ASP/gestionAbsenceMVC/gestionAbsenceMVC/Views/Absences/Edit.cshtml
@model gestionAbsenceMVC.Models.Absence

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Absence</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_A)

        <div class="form-group">
            @Html.LabelFor(model => model.DateA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.type_Ab, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.type_Ab, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.type_Ab, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_S, "id_S", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_S", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_S, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_P, "id_P", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_P", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_P, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.justf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.justf, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("justf", new List<SelectListItem>
    {new SelectListItem  {Text="oui",Selected=true},new SelectListItem  {Text="non"},}, htmlAttributes: new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.justf, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PFF/ASP/gestionAbsenceMVC/gestionAbsenceMVC/Views/Absences/Index.cshtml
@model IEnumerable<gestionAbsenceMVC.Models.Absence>

@{
    ViewBag.Title = "Index";
}

<h2> Absence </h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div class="form-horizontal">
    @using (Html.BeginForm("Index", "Absences", FormMethod.Get))
    {<b>search by :</b>
        @Html.RadioButton("searchBy", "NameT", true)<text>  Name of trainee     </text>
        @Html.RadioButton("searchBy", "Date")       <text>         Date         </text>
        @Html.RadioButton("searchBy", "NameP")      <text>   Name of Professor  </text>
        @Html.RadioButton("searchBy", "Jus")        <text>     Justification    </text>
        @Html.RadioButton("searchBy", "Tyabs")      <text>   type of absence    </text>


        <p>
            @Html.TextBox("search")  <input type="submit" value="search" />
        </p>
    }
    
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DateA)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.type_Ab)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.justf)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prof.nom_P)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Stagiare.nom_S)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DateA)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.type_Ab)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.justf)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prof.nom_P)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Stagiare.nom_S)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id_A }) |
            @Html.ActionLink("Details", "Details", new { id=item.id_A }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id_A })
        </td>
    </tr>
}

</table>